// dart format width=80
import 'dart:typed_data' as i2;

// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class LocalProfiles extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  LocalProfiles(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> singleton = GeneratedColumn<int>(
    'singleton',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1',
    defaultValue: const CustomExpression('1'),
  );
  late final GeneratedColumn<i2.Uint8List> deviceId =
      GeneratedColumn<i2.Uint8List>(
        'device_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<i2.Uint8List> publicKey =
      GeneratedColumn<i2.Uint8List>(
        'public_key',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<String> displayName = GeneratedColumn<String>(
    'display_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> revision = GeneratedColumn<int>(
    'revision',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAtMicros = GeneratedColumn<int>(
    'created_at_micros',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> updatedAtMicros = GeneratedColumn<int>(
    'updated_at_micros',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    singleton,
    deviceId,
    publicKey,
    displayName,
    revision,
    createdAtMicros,
    updatedAtMicros,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'local_profiles';
  @override
  Set<GeneratedColumn> get $primaryKey => {singleton};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  LocalProfiles createAlias(String alias) {
    return LocalProfiles(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(singleton)',
    'CHECK(singleton = 1)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class PinnedPeers extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  PinnedPeers(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<i2.Uint8List> deviceId =
      GeneratedColumn<i2.Uint8List>(
        'device_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<i2.Uint8List> publicKey =
      GeneratedColumn<i2.Uint8List>(
        'public_key',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<String> displayName = GeneratedColumn<String>(
    'display_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> profileRevision = GeneratedColumn<int>(
    'profile_revision',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> profileCreatedAtMicros = GeneratedColumn<int>(
    'profile_created_at_micros',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> profileUpdatedAtMicros = GeneratedColumn<int>(
    'profile_updated_at_micros',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> pinnedAtMicros = GeneratedColumn<int>(
    'pinned_at_micros',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> lastVerifiedAtMicros = GeneratedColumn<int>(
    'last_verified_at_micros',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> trustState = GeneratedColumn<String>(
    'trust_state',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    deviceId,
    publicKey,
    displayName,
    profileRevision,
    profileCreatedAtMicros,
    profileUpdatedAtMicros,
    pinnedAtMicros,
    lastVerifiedAtMicros,
    trustState,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'pinned_peers';
  @override
  Set<GeneratedColumn> get $primaryKey => {deviceId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  PinnedPeers createAlias(String alias) {
    return PinnedPeers(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(device_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class Conversations extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Conversations(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<i2.Uint8List> conversationId =
      GeneratedColumn<i2.Uint8List>(
        'conversation_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<i2.Uint8List> firstParticipantId =
      GeneratedColumn<i2.Uint8List>(
        'first_participant_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<i2.Uint8List> secondParticipantId =
      GeneratedColumn<i2.Uint8List>(
        'second_participant_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<int> createdAtMicros = GeneratedColumn<int>(
    'created_at_micros',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    conversationId,
    firstParticipantId,
    secondParticipantId,
    createdAtMicros,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'conversations';
  @override
  Set<GeneratedColumn> get $primaryKey => {conversationId};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {firstParticipantId, secondParticipantId},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Conversations createAlias(String alias) {
    return Conversations(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(conversation_id)',
    'UNIQUE(first_participant_id, second_participant_id)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class Operations extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Operations(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<i2.Uint8List> operationId =
      GeneratedColumn<i2.Uint8List>(
        'operation_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<int> protocolVersion = GeneratedColumn<int>(
    'protocol_version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<i2.Uint8List> conversationId =
      GeneratedColumn<i2.Uint8List>(
        'conversation_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<i2.Uint8List> authorDeviceId =
      GeneratedColumn<i2.Uint8List>(
        'author_device_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<i2.Uint8List> recipientDeviceId =
      GeneratedColumn<i2.Uint8List>(
        'recipient_device_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<int> authorSequence = GeneratedColumn<int>(
    'author_sequence',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<i2.Uint8List> previousOperationId =
      GeneratedColumn<i2.Uint8List>(
        'previous_operation_id',
        aliasedName,
        true,
        type: DriftSqlType.blob,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<int> authoredAtMicros = GeneratedColumn<int>(
    'authored_at_micros',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> messageText = GeneratedColumn<String>(
    'message_text',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<i2.Uint8List> signature =
      GeneratedColumn<i2.Uint8List>(
        'signature',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<i2.Uint8List> canonicalBytes =
      GeneratedColumn<i2.Uint8List>(
        'canonical_bytes',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<int> receivedAtMicros = GeneratedColumn<int>(
    'received_at_micros',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    operationId,
    protocolVersion,
    conversationId,
    authorDeviceId,
    recipientDeviceId,
    authorSequence,
    previousOperationId,
    authoredAtMicros,
    messageText,
    signature,
    canonicalBytes,
    receivedAtMicros,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'operations';
  @override
  Set<GeneratedColumn> get $primaryKey => {operationId};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {conversationId, authorDeviceId, authorSequence},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Operations createAlias(String alias) {
    return Operations(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(operation_id)',
    'UNIQUE(conversation_id, author_device_id, author_sequence)',
    'FOREIGN KEY(conversation_id)REFERENCES conversations(conversation_id)ON DELETE CASCADE',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class FeedHeads extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  FeedHeads(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<i2.Uint8List> conversationId =
      GeneratedColumn<i2.Uint8List>(
        'conversation_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<i2.Uint8List> authorDeviceId =
      GeneratedColumn<i2.Uint8List>(
        'author_device_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<int> headSequence = GeneratedColumn<int>(
    'head_sequence',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<i2.Uint8List> headOperationId =
      GeneratedColumn<i2.Uint8List>(
        'head_operation_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<int> isQuarantined = GeneratedColumn<int>(
    'is_quarantined',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_quarantined IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  @override
  List<GeneratedColumn> get $columns => [
    conversationId,
    authorDeviceId,
    headSequence,
    headOperationId,
    isQuarantined,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'feed_heads';
  @override
  Set<GeneratedColumn> get $primaryKey => {conversationId, authorDeviceId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  FeedHeads createAlias(String alias) {
    return FeedHeads(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(conversation_id, author_device_id)',
    'FOREIGN KEY(conversation_id)REFERENCES conversations(conversation_id)ON DELETE CASCADE',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class MessageProjections extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  MessageProjections(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<i2.Uint8List> operationId =
      GeneratedColumn<i2.Uint8List>(
        'operation_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<i2.Uint8List> conversationId =
      GeneratedColumn<i2.Uint8List>(
        'conversation_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<i2.Uint8List> authorDeviceId =
      GeneratedColumn<i2.Uint8List>(
        'author_device_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<i2.Uint8List> recipientDeviceId =
      GeneratedColumn<i2.Uint8List>(
        'recipient_device_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<int> authorSequence = GeneratedColumn<int>(
    'author_sequence',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> authoredAtMicros = GeneratedColumn<int>(
    'authored_at_micros',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> messageText = GeneratedColumn<String>(
    'message_text',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> insertedAtMicros = GeneratedColumn<int>(
    'inserted_at_micros',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    operationId,
    conversationId,
    authorDeviceId,
    recipientDeviceId,
    authorSequence,
    authoredAtMicros,
    messageText,
    insertedAtMicros,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'message_projections';
  @override
  Set<GeneratedColumn> get $primaryKey => {operationId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  MessageProjections createAlias(String alias) {
    return MessageProjections(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(operation_id)',
    'FOREIGN KEY(operation_id)REFERENCES operations(operation_id)ON DELETE CASCADE',
    'FOREIGN KEY(conversation_id)REFERENCES conversations(conversation_id)ON DELETE CASCADE',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class RetentionFloors extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  RetentionFloors(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<i2.Uint8List> conversationId =
      GeneratedColumn<i2.Uint8List>(
        'conversation_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<i2.Uint8List> authorDeviceId =
      GeneratedColumn<i2.Uint8List>(
        'author_device_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<int> retainedThroughSequence =
      GeneratedColumn<int>(
        'retained_through_sequence',
        aliasedName,
        false,
        type: DriftSqlType.int,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  @override
  List<GeneratedColumn> get $columns => [
    conversationId,
    authorDeviceId,
    retainedThroughSequence,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'retention_floors';
  @override
  Set<GeneratedColumn> get $primaryKey => {conversationId, authorDeviceId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  RetentionFloors createAlias(String alias) {
    return RetentionFloors(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(conversation_id, author_device_id)',
    'FOREIGN KEY(conversation_id)REFERENCES conversations(conversation_id)ON DELETE CASCADE',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DeliveryAcknowledgements extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DeliveryAcknowledgements(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<i2.Uint8List> conversationId =
      GeneratedColumn<i2.Uint8List>(
        'conversation_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<i2.Uint8List> authorDeviceId =
      GeneratedColumn<i2.Uint8List>(
        'author_device_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<i2.Uint8List> recipientDeviceId =
      GeneratedColumn<i2.Uint8List>(
        'recipient_device_id',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<int> highestSequence = GeneratedColumn<int>(
    'highest_sequence',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> updatedAtMicros = GeneratedColumn<int>(
    'updated_at_micros',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    conversationId,
    authorDeviceId,
    recipientDeviceId,
    highestSequence,
    updatedAtMicros,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'delivery_acknowledgements';
  @override
  Set<GeneratedColumn> get $primaryKey => {
    conversationId,
    authorDeviceId,
    recipientDeviceId,
  };
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DeliveryAcknowledgements createAlias(String alias) {
    return DeliveryAcknowledgements(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(conversation_id, author_device_id, recipient_device_id)',
    'FOREIGN KEY(conversation_id)REFERENCES conversations(conversation_id)ON DELETE CASCADE',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DatabaseAtV1 extends GeneratedDatabase {
  DatabaseAtV1(QueryExecutor e) : super(e);
  late final LocalProfiles localProfiles = LocalProfiles(this);
  late final PinnedPeers pinnedPeers = PinnedPeers(this);
  late final Conversations conversations = Conversations(this);
  late final Operations operations = Operations(this);
  late final FeedHeads feedHeads = FeedHeads(this);
  late final MessageProjections messageProjections = MessageProjections(this);
  late final RetentionFloors retentionFloors = RetentionFloors(this);
  late final DeliveryAcknowledgements deliveryAcknowledgements =
      DeliveryAcknowledgements(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    localProfiles,
    pinnedPeers,
    conversations,
    operations,
    feedHeads,
    messageProjections,
    retentionFloors,
    deliveryAcknowledgements,
  ];
  @override
  StreamQueryUpdateRules get streamUpdateRules => const StreamQueryUpdateRules([
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'conversations',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('operations', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'conversations',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('feed_heads', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'operations',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('message_projections', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'conversations',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('message_projections', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'conversations',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('retention_floors', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'conversations',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [
        TableUpdate('delivery_acknowledgements', kind: UpdateKind.delete),
      ],
    ),
  ]);
  @override
  int get schemaVersion => 1;
}
